#! /bin/sh
### BEGIN INIT INFO
# Provides:          <ica service for iTalc>
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage ica service
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

RETVAL=0
prog="ica"
user="pi"

start() {
  echo "Starting $prog: (service for iTalc)"
  su - $user -c /usr/bin/$prog > /var/log/$prog.log 2>&1
  RETVAL=$?
  [ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
  echo
  exit 0
}
stop() {
  echo "Stopping $prog: (service for iTalc)"
  killproc $prog -TERM
  RETVAL=$?
  [ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
  echo
  exit 0
}
reload() {
  echo "Reloading $prog: (service for iTalc)"
  killproc $prog -HUP
  RETVAL=$?
  echo
  exit 0
}
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    reload
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: service ica {start|restart|reload|status|stop}"
    exit 1
    ;;
esac
